### ISSUE TITLE
URL mismatch in README

### ISSUE THREAD

**Issue by colearendt** [sol-eng/python-examples#6]
From @nrohr

> I noticed that the jupyter notebook example links in the readme for https://github.com/sol-eng/python-examples are switched (interactive <-> non-interactive). I was going to do a PR, but realized I don’t have permission to push branches
> 
> It’s just the URLs in lines 30-31 need switched

**Comment by koverholt** [comment]
Thanks for catching that @nrohr! Fixed in 2f3406c.
